name: WLTPMorphPlugin
main: world.wltp.wltpmorphplugin.Main
version: 1.0-SNAPSHOT
api-version: 1.21
commands:
  morph:
    description: Morph into an block display
    usage: /morph <BLOCK>
  unmorph:
    description: Revert morph
    usage: /unmorph

permissions:
  morph.use:
    description: Allows player to use the /morph command to transform into a block.
    default: op
  morph.unmorph:
    description: Allows player to use the /unmorph command to revert transformation.
    default: op